[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    
# Fix for .mjs files if you have any
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"
    
# Fix for favicon
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
